# Generated by Django 4.1.4 on 2023-03-24 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=4, verbose_name="currency")),
            ],
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "transactionUSD",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="transaction in USD",
                        max_digits=14,
                        verbose_name="Transaction in USD",
                    ),
                ),
                (
                    "transactionValue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        help_text="OPTIONAL transaction value in other currency than USD(",
                        max_digits=14,
                        null=True,
                        verbose_name="Transaction Value",
                    ),
                ),
                (
                    "exchangeRate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="OPTIONAL exchange rate to the USD",
                        max_digits=14,
                        null=True,
                        verbose_name="Exchange Rate",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="OPTIONAL additional info about transaction",
                        max_length=1000,
                        null=True,
                        verbose_name="Description of transaction",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="OPTIONAL",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settlement.currency",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
